# Generated by Django 4.2.7 on 2024-01-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_file', models.CharField(default='', max_length=225)),
                ('src_name', models.CharField(default='', max_length=225)),
                ('src_link', models.CharField(default='', max_length=225)),
                ('result_text', models.CharField(default='', max_length=4096)),
                ('status', models.CharField(default='', max_length=10)),
                ('usage_flag', models.CharField(default='', max_length=10)),
                ('create_at', models.DateTimeField()),
            ],
        ),
    ]
