# Generated by Django 5.0 on 2024-01-03 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.BooleanField(default=False)),
                ('delight', models.IntegerField()),
                ('professor1', models.BooleanField(default=False)),
                ('professor2', models.BooleanField(default=False)),
                ('course', models.IntegerField()),
                ('grade', models.FloatField()),
                ('result', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='calculater',
        ),
    ]
